name: Publish to WinGet

on:
  workflow_dispatch:
    inputs:
      version:
        description: Version to release
        required: true

jobs:
  publish:
    # Action can only be run on windows
    runs-on: windows-latest
    steps:
      - uses: vedantmgoyal2009/winget-releaser@v2
        # https://github.com/vedantmgoyal2009/winget-releaser
        with:
          identifier: ProjectJupyter.JupyterLab
          token: ${{ secrets.WINGET_TOKEN }}
          fork-user: mbektas
          release-tag: ${{ inputs.version }}
